version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: alumniug
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: .  # Usa la ruta actual ya que Dockerfile está aquí
    volumes:
      - .:/app  # Volumen que monta la ruta actual en /app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - DATABASE_URL=postgresql://postgres:root@db:5432/alumniug
    depends_on:
      - db

volumes:
  postgres_data:
